#include <preinit/lib/debug.h>
#include "vmcb_intro.h"

#define VMCB_Z_INTCEPT_LO_OFFSET	3
#define VMCB_Z_INTCEPT_HI_OFFSET	4
#define VMCB_Z_GASID_OFFSET		22
#define VMCB_Z_INT_CTL_OFFSET		24
#define VMCB_Z_VINT_VECTOR_OFFSET	25
#define VMCB_Z_NESTED_CTL_OFFSET	36
#define VMCB_Z_EFER_LO_OFFSET		308
#define VMCB_Z_DR7_LO_OFFSET		344
#define VMCB_Z_DR6_LO_OFFSET		346
#define VMCB_Z_GPAT_LO_OFFSET		410
#define VMCB_Z_GPAT_HI_OFFSET		411

#define SVM_INTR_CTRL_IGN_VTPR_SHIFT	20
#define SVM_INTR_CTRL_IGN_VTPR		(1 << SVM_INTR_CTRL_IGN_VTPR_SHIFT)
#define SVM_INTR_CTRL_VINTR_MASK_SHIFT	24
#define SVM_INTR_CTRL_VINTR_MASK	(1 << SVM_INTR_CTRL_VINTR_MASK_SHIFT)

#define INTERCEPT_INTR			0
#define INTERCEPT_RDTSC			14
#define INTERCEPT_CPUID			18
#define INTERCEPT_HLT			24
#define INTERCEPT_IOIO_PROT		27

#define INTERCEPT_VMRUN			0
#define INTERCEPT_VMMCALL		1
#define INTERCEPT_VMLOAD		2
#define INTERCEPT_VMSAVE		3
#define INTERCEPT_STGI			4
#define INTERCEPT_CLGI			5
#define INTERCEPT_SKINIT		6
#define INTERCEPT_RDTSCP		7
#define INTERCEPT_MONITOR		10
#define INTERCEPT_MWAIT			11
#define INTERCEPT_MWAIT_COND		12

void
vmcb_init(unsigned int mbi_addr)
{
	npt_init(mbi_addr);

	vmcb_write_z(VMCB_Z_DR6_LO_OFFSET, 0xffff0ff0);
	vmcb_write_z(VMCB_Z_DR7_LO_OFFSET, 0x00000400);
	vmcb_write_z(VMCB_Z_EFER_LO_OFFSET, 1 << 12);
	vmcb_write_z(VMCB_Z_GPAT_LO_OFFSET, 0x00070406);
	vmcb_write_z(VMCB_Z_GPAT_HI_OFFSET, 0x00070406);

	vmcb_write_z(VMCB_Z_GASID_OFFSET, 1);
	vmcb_write_z(VMCB_Z_NESTED_CTL_OFFSET, 1);
	vmcb_write_z(VMCB_Z_INT_CTL_OFFSET,
		     SVM_INTR_CTRL_VINTR_MASK);

	vmcb_write_z(VMCB_Z_INTCEPT_LO_OFFSET,
		     (1UL << INTERCEPT_INTR) | (1UL << INTERCEPT_RDTSC) |
		     (1UL << INTERCEPT_CPUID) | (1UL << INTERCEPT_HLT) |
		     (1UL << INTERCEPT_IOIO_PROT));
	vmcb_write_z(VMCB_Z_INTCEPT_HI_OFFSET,
		     (1UL << INTERCEPT_VMRUN) | (1UL << INTERCEPT_VMMCALL) |
		     (1UL << INTERCEPT_VMLOAD) | (1UL << INTERCEPT_VMSAVE) |
		     (1UL << INTERCEPT_STGI) | (1UL << INTERCEPT_CLGI) |
		     (1UL << INTERCEPT_SKINIT) | (1UL << INTERCEPT_RDTSCP) |
		     (1UL << INTERCEPT_MONITOR) | (1UL << INTERCEPT_MWAIT) |
		     (1UL << INTERCEPT_MWAIT_COND));
}
