#ifndef _KERN_DEV_CONS_KBD_H_
#define _KERN_DEV_CONS_KBD_H_

#ifdef _KERN_

#define CONS_KEYCODE_MASK	0x00ff
#define CONS_KBDSTAT_MASK	0xff00
#define CONS_KBDSTAT_SHIFT	8

#define CONS_GET_KEYCODE(x)			\
	((uint8_t) ((x) & CONS_KEYCODE_MASK))
#define CONS_GET_KDBSTAT(x)						\
	((uint8_t) (((x) & CONS_KBDSTAT_MASK) >> CONS_KBDSTAT_SHIFT))
#define CONS_MAKE_KBDINPUT(s, k)					\
	((((uint16_t) (s) << CONS_KBDSTAT_SHIFT) & CONS_KBDSTAT_MASK) |	\
	 ((uint16_t) (k) & CONS_KEYCODE_MASK))

typedef enum {
	KEY_NOP = 0,
	KEY_ESC,
	KEY_F1, KEY_F2, KEY_F3, KEY_F4,	KEY_F5, KEY_F6,
	KEY_F7, KEY_F8,	KEY_F9, KEY_F10, KEY_F11, KEY_F12,
	KEY_TIDE,
	KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
	KEY_MINUS, KEY_PLUS, KEY_BACKSPACE,
	KEY_TAB, KEY_L_BRACK, KEY_R_BRACK, KEY_BACKSLASH,
	KEY_CAPSLOCK, KEY_SEMICOLON, KEY_QUOTE, KEY_ENTER,
	KEY_L_SHIFT,  KEY_R_SHIFT,
	KEY_COMMA, KEY_DOT, KEY_SLASH,
	KEY_L_CTRL, KEY_R_CTRL,
	KEY_L_ALT, KEY_R_ALT,
	KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J,
	KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T,
	KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,
	KEY_SPACE,
	KEY_PRTSCN, KEY_SCROLLLOCK, KEY_PAUSE,
	KEY_INSERT, KEY_HOME, KEY_PAGEUP,
	KEY_DELETE, KEY_END, KEY_PAGEDOWN,
	KEY_UP, KEY_LEFT, KEY_DOWN, KEY_RIGHT,
	KEY_NUMLOCK,
	KEY_KP_DIV, KEY_KP_MULT, KEY_KP_MINUS,
	KEY_KP_PLUS, KEY_KP_DOT, KEY_KP_ENTER,
	KEY_KP_0, KEY_KP_1, KEY_KP_2, KEY_KP_3, KEY_KP_4,
	KEY_KP_5, KEY_KP_6, KEY_KP_7, KEY_KP_8, KEY_KP_9,
	KEY_L_WIN, KEY_R_WIN, KEY_MENU,
	__KEY_MAX
} keycode_t;

#define KBS_RELEASE	(1 << 0)
#define KBS_SHIFT	(1 << 1)
#define KBS_ALT		(1 << 2)
#define KBS_CTRL	(1 << 3)
#define KBS_WIN		(1 << 4)
#define KBS_CAPSLOCK	(1 << 5)
#define KBS_SCROLLLOCK	(1 << 6)
#define KBS_NUMLOCK	(1 << 7)

#endif /* _KERN_ */

#endif /* !_KERN_DEV_CONS_KBD_H_ */
