
//guest registers
enum {
        GUEST_EAX, GUEST_EBX, GUEST_ECX, GUEST_EDX, GUEST_ESI, GUEST_EDI,
        GUEST_EBP, GUEST_ESP, GUEST_EIP, GUEST_EFLAGS,
        GUEST_CR0, GUEST_CR2, GUEST_CR3, GUEST_CR4,
        GUEST_MAX_REG
};

//guest segments
enum {
        GUEST_CS, GUEST_DS, GUEST_ES, GUEST_FS, GUEST_GS, GUEST_SS,
        GUEST_LDTR, GUEST_TR, GUEST_GDTR, GUEST_IDTR,
        GUEST_MAX_SEG_DESC
};
